"""add project reward packages

Revision ID: 14657b61f39d
Revises: cc5ebf856db3
Create Date: 2026-05-28 09:29:48.748133
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '14657b61f39d'
down_revision: str | None = 'cc5ebf856db3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('limit_count', sa.Integer(), nullable=True),
    sa.Column('claimed_count', sa.Integer(), nullable=False),
    sa.Column('requires_delivery', sa.Boolean(), nullable=False),
    sa.Column('estimated_delivery_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_rewards_id'), 'project_rewards', ['id'], unique=False)
    op.create_index(op.f('ix_project_rewards_project_id'), 'project_rewards', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_rewards_project_id'), table_name='project_rewards')
    op.drop_index(op.f('ix_project_rewards_id'), table_name='project_rewards')
    op.drop_table('project_rewards')
    # ### end Alembic commands ###
