"""add complaint system

Revision ID: 494b37c9a088
Revises: a607bd205ab0
Create Date: 2026-05-28 13:17:57.275630
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '494b37c9a088'
down_revision: str | None = 'a607bd205ab0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Enum('FRAUD', 'FALSE_INFORMATION', 'NO_REPORTS', 'INSULTS', 'PROHIBITED_CONTENT', 'OTHER', name='complaint_reason', native_enum=False), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'RESOLVED', 'REJECTED', name='complaint_status', native_enum=False), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('moderator_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_comment_id'), 'complaints', ['comment_id'], unique=False)
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_moderator_id'), 'complaints', ['moderator_id'], unique=False)
    op.create_index(op.f('ix_complaints_project_id'), 'complaints', ['project_id'], unique=False)
    op.create_index(op.f('ix_complaints_reason'), 'complaints', ['reason'], unique=False)
    op.create_index(op.f('ix_complaints_reporter_id'), 'complaints', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_reporter_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_reason'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_project_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_moderator_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_comment_id'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
