"""add static translations dictionary

Revision ID: 4cf762b7e39b
Revises: cb6fe8c32436
Create Date: 2026-05-28 13:59:37.053058
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4cf762b7e39b'
down_revision: str | None = 'cb6fe8c32436'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('ru', sa.Text(), nullable=False),
    sa.Column('kg', sa.Text(), nullable=True),
    sa.Column('en', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'key', name='uq_static_translation_namespace_key')
    )
    op.create_index(op.f('ix_static_translations_id'), 'static_translations', ['id'], unique=False)
    op.create_index(op.f('ix_static_translations_key'), 'static_translations', ['key'], unique=False)
    op.create_index(op.f('ix_static_translations_namespace'), 'static_translations', ['namespace'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_static_translations_namespace'), table_name='static_translations')
    op.drop_index(op.f('ix_static_translations_key'), table_name='static_translations')
    op.drop_index(op.f('ix_static_translations_id'), table_name='static_translations')
    op.drop_table('static_translations')
    # ### end Alembic commands ###
