"""add project reports

Revision ID: 5c1ed74a2f5d
Revises: 90f62261f29d
Create Date: 2026-05-28 09:45:07.310093
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5c1ed74a2f5d'
down_revision: str | None = '90f62261f29d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('expense_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'HIDDEN', name='report_status', native_enum=False), nullable=False),
    sa.Column('moderator_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_reports_author_id'), 'project_reports', ['author_id'], unique=False)
    op.create_index(op.f('ix_project_reports_id'), 'project_reports', ['id'], unique=False)
    op.create_index(op.f('ix_project_reports_language'), 'project_reports', ['language'], unique=False)
    op.create_index(op.f('ix_project_reports_project_id'), 'project_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_reports_status'), 'project_reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_reports_status'), table_name='project_reports')
    op.drop_index(op.f('ix_project_reports_project_id'), table_name='project_reports')
    op.drop_index(op.f('ix_project_reports_language'), table_name='project_reports')
    op.drop_index(op.f('ix_project_reports_id'), table_name='project_reports')
    op.drop_index(op.f('ix_project_reports_author_id'), table_name='project_reports')
    op.drop_table('project_reports')
    # ### end Alembic commands ###
