"""add project and translation models

Revision ID: 6e769989958e
Revises: cac8cf805e16
Create Date: 2026-05-28 06:50:00.426774
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6e769989958e'
down_revision: str | None = 'cac8cf805e16'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'FUNDRAISING', 'FUNDED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', 'FROZEN', name='project_status', native_enum=False), nullable=False),
    sa.Column('project_type', sa.Enum('DONATION', 'REWARD', 'PREORDER', 'BUSINESS_SUPPORT', 'INVESTMENT_DISABLED', name='project_type', native_enum=False), nullable=False),
    sa.Column('funding_type', sa.Enum('ALL_OR_NOTHING', 'FLEXIBLE_FUNDING', name='funding_type', native_enum=False), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('goal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('cover_image_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('frozen_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_author_id'), 'projects', ['author_id'], unique=False)
    op.create_index(op.f('ix_projects_funding_type'), 'projects', ['funding_type'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_project_type'), 'projects', ['project_type'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('project_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('refund_policy', sa.Text(), nullable=True),
    sa.Column('reward_description', sa.Text(), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'language', name='uq_project_translation_language')
    )
    op.create_index(op.f('ix_project_translations_id'), 'project_translations', ['id'], unique=False)
    op.create_index(op.f('ix_project_translations_language'), 'project_translations', ['language'], unique=False)
    op.create_index(op.f('ix_project_translations_project_id'), 'project_translations', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_translations_project_id'), table_name='project_translations')
    op.drop_index(op.f('ix_project_translations_language'), table_name='project_translations')
    op.drop_index(op.f('ix_project_translations_id'), table_name='project_translations')
    op.drop_table('project_translations')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_funding_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_author_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
