"""add project updates

Revision ID: 90f62261f29d
Revises: 14657b61f39d
Create Date: 2026-05-28 09:39:10.165317
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '90f62261f29d'
down_revision: str | None = '14657b61f39d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_updates_author_id'), 'project_updates', ['author_id'], unique=False)
    op.create_index(op.f('ix_project_updates_id'), 'project_updates', ['id'], unique=False)
    op.create_index(op.f('ix_project_updates_language'), 'project_updates', ['language'], unique=False)
    op.create_index(op.f('ix_project_updates_project_id'), 'project_updates', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_updates_project_id'), table_name='project_updates')
    op.drop_index(op.f('ix_project_updates_language'), table_name='project_updates')
    op.drop_index(op.f('ix_project_updates_id'), table_name='project_updates')
    op.drop_index(op.f('ix_project_updates_author_id'), table_name='project_updates')
    op.drop_table('project_updates')
    # ### end Alembic commands ###
