"""add test refund service

Revision ID: a649cc513345
Revises: aac9bf1f1640
Create Date: 2026-05-28 10:23:09.321525
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a649cc513345'
down_revision: str | None = 'aac9bf1f1640'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_attempt_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_created_by_id'), 'refunds', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_attempt_id'), 'refunds', ['payment_attempt_id'], unique=False)
    op.create_index(op.f('ix_refunds_project_id'), 'refunds', ['project_id'], unique=False)
    op.create_index(op.f('ix_refunds_user_id'), 'refunds', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_user_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_project_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_attempt_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_created_by_id'), table_name='refunds')
    op.drop_table('refunds')
    # ### end Alembic commands ###
