"""add platform fee rules

Revision ID: aac9bf1f1640
Revises: c9a66ed2a668
Create Date: 2026-05-28 10:03:46.424194
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'aac9bf1f1640'
down_revision: str | None = 'c9a66ed2a668'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_fee_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_type', sa.Enum('DONATION', 'REWARD', 'PREORDER', 'BUSINESS_SUPPORT', 'INVESTMENT_DISABLED', name='platform_fee_project_type', native_enum=False), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_fee_rules_id'), 'platform_fee_rules', ['id'], unique=False)
    op.create_index(op.f('ix_platform_fee_rules_project_type'), 'platform_fee_rules', ['project_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_fee_rules_project_type'), table_name='platform_fee_rules')
    op.drop_index(op.f('ix_platform_fee_rules_id'), table_name='platform_fee_rules')
    op.drop_table('platform_fee_rules')
    # ### end Alembic commands ###
