"""add immutable ledger entries

Revision ID: c9a66ed2a668
Revises: 0626a7c9eb93
Create Date: 2026-05-28 10:00:46.182299
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c9a66ed2a668'
down_revision: str | None = '0626a7c9eb93'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payment_attempt_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('PROJECT_GROSS', 'PLATFORM_FEE', 'PROJECT_NET', 'REFUND', 'ADMIN_ADJUSTMENT', name='ledger_entry_type', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('POSTED', 'VOIDED', name='ledger_entry_status', native_enum=False), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_created_at'), 'ledger_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_created_by_id'), 'ledger_entries', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_id'), 'ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_payment_attempt_id'), 'ledger_entries', ['payment_attempt_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_project_id'), 'ledger_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_status'), 'ledger_entries', ['status'], unique=False)
    op.create_index(op.f('ix_ledger_entries_type'), 'ledger_entries', ['type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_user_id'), 'ledger_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_user_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_type'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_status'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_project_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_payment_attempt_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_created_by_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_created_at'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
