"""add multilingual banners

Revision ID: cb6fe8c32436
Revises: d73e7a204ac0
Create Date: 2026-05-28 13:57:21.541886
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cb6fe8c32436'
down_revision: str | None = 'd73e7a204ac0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('placement', sa.Enum('HOME_HERO', 'HOME_SECONDARY', 'PROJECTS_TOP', 'CATEGORY_TOP', 'TEST_MODE_NOTICE', name='banner_placement', native_enum=False), nullable=False),
    sa.Column('image_file_id', sa.Integer(), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_file_id'], ['files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banners_id'), 'banners', ['id'], unique=False)
    op.create_index(op.f('ix_banners_image_file_id'), 'banners', ['image_file_id'], unique=False)
    op.create_index(op.f('ix_banners_placement'), 'banners', ['placement'], unique=False)
    op.create_index(op.f('ix_banners_slug'), 'banners', ['slug'], unique=True)
    op.create_table('banner_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banner_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('cta_text', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['banner_id'], ['banners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('banner_id', 'language', name='uq_banner_translation_language')
    )
    op.create_index(op.f('ix_banner_translations_banner_id'), 'banner_translations', ['banner_id'], unique=False)
    op.create_index(op.f('ix_banner_translations_id'), 'banner_translations', ['id'], unique=False)
    op.create_index(op.f('ix_banner_translations_language'), 'banner_translations', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banner_translations_language'), table_name='banner_translations')
    op.drop_index(op.f('ix_banner_translations_id'), table_name='banner_translations')
    op.drop_index(op.f('ix_banner_translations_banner_id'), table_name='banner_translations')
    op.drop_table('banner_translations')
    op.drop_index(op.f('ix_banners_slug'), table_name='banners')
    op.drop_index(op.f('ix_banners_placement'), table_name='banners')
    op.drop_index(op.f('ix_banners_image_file_id'), table_name='banners')
    op.drop_index(op.f('ix_banners_id'), table_name='banners')
    op.drop_table('banners')
    # ### end Alembic commands ###
