"""add cms pages

Revision ID: d73e7a204ac0
Revises: f4af51264341
Create Date: 2026-05-28 13:54:46.705919
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd73e7a204ac0'
down_revision: str | None = 'f4af51264341'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_pages_id'), 'cms_pages', ['id'], unique=False)
    op.create_index(op.f('ix_cms_pages_slug'), 'cms_pages', ['slug'], unique=True)
    op.create_table('cms_page_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['cms_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'language', name='uq_cms_page_translation_language')
    )
    op.create_index(op.f('ix_cms_page_translations_id'), 'cms_page_translations', ['id'], unique=False)
    op.create_index(op.f('ix_cms_page_translations_language'), 'cms_page_translations', ['language'], unique=False)
    op.create_index(op.f('ix_cms_page_translations_page_id'), 'cms_page_translations', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cms_page_translations_page_id'), table_name='cms_page_translations')
    op.drop_index(op.f('ix_cms_page_translations_language'), table_name='cms_page_translations')
    op.drop_index(op.f('ix_cms_page_translations_id'), table_name='cms_page_translations')
    op.drop_table('cms_page_translations')
    op.drop_index(op.f('ix_cms_pages_slug'), table_name='cms_pages')
    op.drop_index(op.f('ix_cms_pages_id'), table_name='cms_pages')
    op.drop_table('cms_pages')
    # ### end Alembic commands ###
